// Generated by tools/generate_abi.py; do not edit.

/// ABI constant `REPLIA_C_ABI_VERSION`.
pub const REPLIA_C_ABI_VERSION: u32 = 1;
/// ABI constant `REPLIA_OK`.
pub const REPLIA_OK: i32 = 0;
/// ABI constant `REPLIA_INVALID_ARGUMENT`.
pub const REPLIA_INVALID_ARGUMENT: i32 = 1;
/// ABI constant `REPLIA_INVALID_UTF8`.
pub const REPLIA_INVALID_UTF8: i32 = 2;
/// ABI constant `REPLIA_INVALID_RANGE`.
pub const REPLIA_INVALID_RANGE: i32 = 3;
/// ABI constant `REPLIA_CAPACITY`.
pub const REPLIA_CAPACITY: i32 = 4;
/// ABI constant `REPLIA_INVALID_STATE`.
pub const REPLIA_INVALID_STATE: i32 = 5;
/// ABI constant `REPLIA_UNSUITABLE_TERMINAL`.
pub const REPLIA_UNSUITABLE_TERMINAL: i32 = 6;
/// ABI constant `REPLIA_IO`.
pub const REPLIA_IO: i32 = 7;
/// ABI constant `REPLIA_BUFFER_TOO_SMALL`.
pub const REPLIA_BUFFER_TOO_SMALL: i32 = 8;
/// ABI constant `REPLIA_ABI_MISMATCH`.
pub const REPLIA_ABI_MISMATCH: i32 = 9;
/// ABI constant `REPLIA_BUSY`.
pub const REPLIA_BUSY: i32 = 10;
/// ABI constant `REPLIA_INTERNAL`.
pub const REPLIA_INTERNAL: i32 = 11;
/// ABI constant `REPLIA_INVALID_TEXT`.
pub const REPLIA_INVALID_TEXT: i32 = 12;
/// ABI constant `REPLIA_HISTORY_DISABLED`.
pub const REPLIA_HISTORY_DISABLED: i32 = 13;
/// ABI constant `REPLIA_INVALID_SEQUENCE`.
pub const REPLIA_INVALID_SEQUENCE: i32 = 14;
/// ABI constant `REPLIA_EVENT_NONE`.
pub const REPLIA_EVENT_NONE: u32 = 0;
/// ABI constant `REPLIA_EVENT_SUBMITTED`.
pub const REPLIA_EVENT_SUBMITTED: u32 = 1;
/// ABI constant `REPLIA_EVENT_INTERRUPTED`.
pub const REPLIA_EVENT_INTERRUPTED: u32 = 2;
/// ABI constant `REPLIA_EVENT_END_OF_INPUT`.
pub const REPLIA_EVENT_END_OF_INPUT: u32 = 3;
/// ABI constant `REPLIA_EVENT_COMPLETION_REQUESTED`.
pub const REPLIA_EVENT_COMPLETION_REQUESTED: u32 = 4;
/// ABI constant `REPLIA_EVENT_EDIT_REJECTED`.
pub const REPLIA_EVENT_EDIT_REJECTED: u32 = 5;
/// ABI constant `REPLIA_ROLE_DEFAULT`.
pub const REPLIA_ROLE_DEFAULT: u32 = 0;
/// ABI constant `REPLIA_ROLE_STRONG`.
pub const REPLIA_ROLE_STRONG: u32 = 1;
/// ABI constant `REPLIA_ROLE_ACCENT`.
pub const REPLIA_ROLE_ACCENT: u32 = 2;
/// ABI constant `REPLIA_ROLE_DIM`.
pub const REPLIA_ROLE_DIM: u32 = 3;
/// ABI constant `REPLIA_ROLE_SUCCESS`.
pub const REPLIA_ROLE_SUCCESS: u32 = 4;
/// ABI constant `REPLIA_ROLE_WARNING`.
pub const REPLIA_ROLE_WARNING: u32 = 5;
/// ABI constant `REPLIA_ROLE_ERROR`.
pub const REPLIA_ROLE_ERROR: u32 = 6;
/// Creation limits. Zero-initialize, then set struct_size, abi_version and desired limits.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct RepliaConfig {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `abi_version`; see the installed header contract.
    pub abi_version: u32,
    /// ABI field `max_input_bytes`; see the installed header contract.
    pub max_input_bytes: u64,
    /// ABI field `history_entries`; see the installed header contract.
    pub history_entries: u64,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: [u64; 2],
}
/// Poll output. Before EVERY poll/interrupt: zero-initialize and set struct_size and abi_version.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct RepliaEvent {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `abi_version`; see the installed header contract.
    pub abi_version: u32,
    /// ABI field `kind`; see the installed header contract.
    pub kind: u32,
    /// ABI field `status`; see the installed header contract.
    pub status: i32,
    /// ABI field `text_bytes`; see the installed header contract.
    pub text_bytes: u64,
    /// ABI field `cursor_bytes`; see the installed header contract.
    pub cursor_bytes: u64,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: [u64; 2],
}
