#include "replai.h"
#include <stdio.h>
int main(void) {
    printf("REPLAI_C_ABI_VERSION=%lld\n", (long long)REPLAI_C_ABI_VERSION);
    printf("REPLAI_OK=%lld\n", (long long)REPLAI_OK);
    printf("REPLAI_INVALID_ARGUMENT=%lld\n", (long long)REPLAI_INVALID_ARGUMENT);
    printf("REPLAI_INVALID_UTF8=%lld\n", (long long)REPLAI_INVALID_UTF8);
    printf("REPLAI_INVALID_RANGE=%lld\n", (long long)REPLAI_INVALID_RANGE);
    printf("REPLAI_CAPACITY=%lld\n", (long long)REPLAI_CAPACITY);
    printf("REPLAI_INVALID_STATE=%lld\n", (long long)REPLAI_INVALID_STATE);
    printf("REPLAI_UNSUITABLE_TERMINAL=%lld\n", (long long)REPLAI_UNSUITABLE_TERMINAL);
    printf("REPLAI_IO=%lld\n", (long long)REPLAI_IO);
    printf("REPLAI_BUFFER_TOO_SMALL=%lld\n", (long long)REPLAI_BUFFER_TOO_SMALL);
    printf("REPLAI_ABI_MISMATCH=%lld\n", (long long)REPLAI_ABI_MISMATCH);
    printf("REPLAI_BUSY=%lld\n", (long long)REPLAI_BUSY);
    printf("REPLAI_INTERNAL=%lld\n", (long long)REPLAI_INTERNAL);
    printf("REPLAI_INVALID_TEXT=%lld\n", (long long)REPLAI_INVALID_TEXT);
    printf("REPLAI_HISTORY_DISABLED=%lld\n", (long long)REPLAI_HISTORY_DISABLED);
    printf("REPLAI_INVALID_SEQUENCE=%lld\n", (long long)REPLAI_INVALID_SEQUENCE);
    printf("REPLAI_EVENT_NONE=%lld\n", (long long)REPLAI_EVENT_NONE);
    printf("REPLAI_EVENT_SUBMITTED=%lld\n", (long long)REPLAI_EVENT_SUBMITTED);
    printf("REPLAI_EVENT_INTERRUPTED=%lld\n", (long long)REPLAI_EVENT_INTERRUPTED);
    printf("REPLAI_EVENT_END_OF_INPUT=%lld\n", (long long)REPLAI_EVENT_END_OF_INPUT);
    printf("REPLAI_EVENT_COMPLETION_REQUESTED=%lld\n", (long long)REPLAI_EVENT_COMPLETION_REQUESTED);
    printf("REPLAI_EVENT_EDIT_REJECTED=%lld\n", (long long)REPLAI_EVENT_EDIT_REJECTED);
    printf("REPLAI_ROLE_DEFAULT=%lld\n", (long long)REPLAI_ROLE_DEFAULT);
    printf("REPLAI_ROLE_STRONG=%lld\n", (long long)REPLAI_ROLE_STRONG);
    printf("REPLAI_ROLE_ACCENT=%lld\n", (long long)REPLAI_ROLE_ACCENT);
    printf("REPLAI_ROLE_DIM=%lld\n", (long long)REPLAI_ROLE_DIM);
    printf("REPLAI_ROLE_SUCCESS=%lld\n", (long long)REPLAI_ROLE_SUCCESS);
    printf("REPLAI_ROLE_WARNING=%lld\n", (long long)REPLAI_ROLE_WARNING);
    printf("REPLAI_ROLE_ERROR=%lld\n", (long long)REPLAI_ROLE_ERROR);
    printf("replai_config.size=%zu\n", sizeof(replai_config));
    printf("replai_config.align=%zu\n", _Alignof(replai_config));
    printf("replai_config.struct_size=%zu\n", offsetof(replai_config, struct_size));
    printf("replai_config.abi_version=%zu\n", offsetof(replai_config, abi_version));
    printf("replai_config.max_input_bytes=%zu\n", offsetof(replai_config, max_input_bytes));
    printf("replai_config.history_entries=%zu\n", offsetof(replai_config, history_entries));
    printf("replai_config.reserved=%zu\n", offsetof(replai_config, reserved));
    printf("replai_event.size=%zu\n", sizeof(replai_event));
    printf("replai_event.align=%zu\n", _Alignof(replai_event));
    printf("replai_event.struct_size=%zu\n", offsetof(replai_event, struct_size));
    printf("replai_event.abi_version=%zu\n", offsetof(replai_event, abi_version));
    printf("replai_event.kind=%zu\n", offsetof(replai_event, kind));
    printf("replai_event.status=%zu\n", offsetof(replai_event, status));
    printf("replai_event.text_bytes=%zu\n", offsetof(replai_event, text_bytes));
    printf("replai_event.cursor_bytes=%zu\n", offsetof(replai_event, cursor_bytes));
    printf("replai_event.reserved=%zu\n", offsetof(replai_event, reserved));
    return 0;
}
