#!/usr/bin/env python3
"""Deterministic narrow ABI records/header/probes; --check rejects checked-in drift."""
import argparse
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SPEC = json.loads((ROOT / "api/c-abi.json").read_text())
NAMES = {"u8": "uint8_t", "u32": "uint32_t", "i32": "int32_t", "u64": "uint64_t", "usize": "size_t", "Handle": "replia_handle"}
NAMES.update({r["name"]: r["c_name"] for r in SPEC["records"]})

def ctype(t):
    if t.startswith("*const "):
        return "const " + ctype(t[7:]) + " *"
    if t.startswith("*mut "):
        return ctype(t[5:]) + " *"
    return NAMES[t]

def outputs():
    header = ['/* SPDX-License-Identifier: MIT', ' * Copyright (c) 2026 YAI Labs', ' * Generated by tools/generate_abi.py from api/c-abi.json.', ' * Pre-release Linux ABI. See docs/c-api.md for ownership and failure rules.', ' * All calls on a handle MUST be serialized by the caller.', ' * Non-NULL pointers must be live, aligned and valid for their stated extent.', ' * Input/output regions must not overlap. Lengths are bytes; no implicit strlen.', ' * NULL spans are permitted only at zero length. No text is NUL-terminated.', ' * Reserved fields must be zero. Struct size/version must match exactly.', ' * INTERNAL means close/destroy only. No call is async-signal-safe.', ' */', '#ifndef REPLIA_H', '#define REPLIA_H', '#include <stddef.h>', '#include <stdint.h>', '#ifdef __cplusplus', 'extern "C" {', '#endif', 'typedef struct replia_handle replia_handle;', 'typedef int32_t replia_status;', 'typedef uint32_t replia_event_kind;', 'typedef uint32_t replia_style_role;']
    rust = ['// Generated by tools/generate_abi.py; do not edit.', '']
    cprobe = ['#include "replia.h"', '#include <stdio.h>', 'int main(void) {']
    rprobe = ['use replia_c::*;', 'fn main() {']
    signatures = ['// Generated signature checks connect the header schema to every exported Rust function.']
    for name, typ, value in SPEC['constants']:
        header.append(f'#define {name} {value}')
        rust += [f'/// ABI constant `{name}`.', f'pub const {name}: {typ} = {value};']
        cprobe.append(f'    printf("{name}=%lld\\n", (long long){name});')
        rprobe.append(f'    println!("{name}={{}}", {name});')
    for r in SPEC['records']:
        n, c = r['name'], r['c_name']
        header += [f'/* {r["doc"]} */', f'typedef struct {c} {{']
        rust += [f'/// {r["doc"]}', '#[repr(C)]', '#[derive(Clone, Copy, Debug)]', f'pub struct {n} {{']
        for field, typ in r['fields']:
            declaration = f'uint64_t {field}[2]' if typ == '[u64; 2]' else f'{ctype(typ)} {field}'
            header.append(f'    {declaration};')
            rust += [f'    /// ABI field `{field}`; see the installed header contract.', f'    pub {field}: {typ},']
        header.append(f'}} {c};')
        rust.append('}')
        cprobe += [f'    printf("{c}.size=%zu\\n", sizeof({c}));', f'    printf("{c}.align=%zu\\n", _Alignof({c}));']
        rprobe += [f'    println!("{c}.size={{}}", std::mem::size_of::<{n}>());', f'    println!("{c}.align={{}}", std::mem::align_of::<{n}>());']
        for field, _ in r['fields']:
            cprobe.append(f'    printf("{c}.{field}=%zu\\n", offsetof({c}, {field}));')
            rprobe.append(f'    println!("{c}.{field}={{}}", std::mem::offset_of!({n}, {field}));')
    for f in SPEC['functions']:
        header += [f'/* {f["doc"]} */', f'replia_status {f["name"]}(' + ', '.join(f'{ctype(t)} {n}' for n, t in f['params']) + ');']
        signatures.append(f'const _: unsafe extern "C" fn(' + ', '.join(t for _, t in f['params']) + f') -> i32 = {f["name"]};')
    header += ['#ifdef __cplusplus', '}', '#endif', '#endif']
    cprobe += ['    return 0;', '}']
    rprobe.append('}')
    files = {'include/replia.h': header, 'crates/replia-c/src/abi.rs': rust, 'crates/replia-c/src/signatures.rs': signatures, 'tests/c/layout.c': cprobe, 'crates/replia-c/examples/layout.rs': ['//! Executable Rust side of the C/Rust ABI layout comparison.'] + rprobe}
    for path, lines in files.items():
        data = '\n'.join(lines) + '\n'
        if path.endswith('.rs'):
            data = subprocess.run(['rustfmt', '--edition', '2024'], input=data, text=True, capture_output=True, check=True).stdout
        yield ROOT / path, data

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, text in outputs():
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'ABI drift: {path.relative_to(ROOT)}')
        else:
            path.write_text(text)
